### ISSUE TITLE
请问是否可以支持IPV6上传

### ISSUE THREAD

**Issue by wintopic** [InfpHub/Raptor#11]
普通家庭宽带对IPV6上传不限速，这样可以极大提升体验度，也可以作为宣传点。

**Comment by InfpPointPlus** [comment]
> 普通家庭宽带对IPV6上传不限速，这样可以极大提升体验度，也可以作为宣传点。

感谢您的建议，将在下个版本尝试启用 IPV6 的支持。需要重新编译 Curl 库以及部分代码调整。

**Comment by InfpHub** [comment]
Raptor 2024.2.0 现已发布。支持 IPV4 和 IPV6 以及自动检测。
