### ISSUE TITLE
能否增加对字体的兼容性

### ISSUE THREAD

**Issue by freedomspiritJohn** [InfpHub/Raptor#12]
我觉得微软雅黑比较丑，于是用misans替换了微软雅黑，别的软件没出现乱码问题，但是打开Raptor后出现字体乱码，所以可以增加兼容性吗，挺喜欢misans字体的。
![image](https://github.com/InfpPointPlus/Raptor/assets/129288685/6580865c-5396-4ba1-8ec7-ba157e1cc607)

**Comment by InfpPointPlus** [comment]
> 我觉得微软雅黑比较丑，于是用misans替换了微软雅黑，别的软件没出现乱码问题，但是打开Raptor后出现字体乱码，所以可以增加兼容性吗，挺喜欢misans字体的。
> ![image](https://github.com/InfpPointPlus/Raptor/assets/129288685/6580865c-5396-4ba1-8ec7-ba157e1cc607)
> 

麻烦您提供一下该字体，这边测试下。并尝试处理兼容性。

**Comment by freedomspiritJohn** [comment]
> > 我觉得微软雅黑比较丑，于是用misans替换了微软雅黑，别的软件没出现乱码问题，但是打开Raptor后出现字体乱码，所以可以增加兼容性吗，挺喜欢misans字体的。
> > ![image](https://private-user-images.githubusercontent.com/129288685/306300621-6580865c-5396-4ba1-8ec7-ba157e1cc607.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0OTY1MTQsIm5iZiI6MTcwODQ5NjIxNCwicGF0aCI6Ii8xMjkyODg2ODUvMzA2MzAwNjIxLTY1ODA4NjVjLTUzOTYtNGJhMS04ZWM3LWJhMTU3ZTFjYzYwNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyMVQwNjE2NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NGQxNzg2NTY4OGU3ZDcxNTUwNTI1NTkzMDExMjM3NDkwMjEyMDU5Y2ZlNGE5ZGM3ZTI3NzRjZmJkZDIyNWZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qf5tULi39bb6tEkMfi_F_hfd3zUpYMgnB1E6MO_Tnio)
> 
> 麻烦您提供一下该字体，这边测试下。并尝试处理兼容性。

https://www.swisstransfer.com/d/9c0851f1-2237-4624-a916-736b5f2a1d49
这是字体文件下载地址，因为需要对微软雅黑进行替换，所以字体信息都改成了雅黑的信息。原版misans可在小米官网下载一搜就有

**Comment by InfpHub** [comment]
> > > 我觉得微软雅黑比较丑，于是用misans替换了微软雅黑，别的软件没出现乱码问题，但是打开Raptor后出现字体乱码，所以可以增加兼容性吗，挺喜欢misans字体的。
> > > ![image](https://private-user-images.githubusercontent.com/129288685/306300621-6580865c-5396-4ba1-8ec7-ba157e1cc607.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0OTY1MTQsIm5iZiI6MTcwODQ5NjIxNCwicGF0aCI6Ii8xMjkyODg2ODUvMzA2MzAwNjIxLTY1ODA4NjVjLTUzOTYtNGJhMS04ZWM3LWJhMTU3ZTFjYzYwNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyMVQwNjE2NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NGQxNzg2NTY4OGU3ZDcxNTUwNTI1NTkzMDExMjM3NDkwMjEyMDU5Y2ZlNGE5ZGM3ZTI3NzRjZmJkZDIyNWZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qf5tULi39bb6tEkMfi_F_hfd3zUpYMgnB1E6MO_Tnio)
> > 
> > 
> > 麻烦您提供一下该字体，这边测试下。并尝试处理兼容性。
> 
> https://www.swisstransfer.com/d/9c0851f1-2237-4624-a916-736b5f2a1d49 这是字体文件下载地址，因为需要对微软雅黑进行替换，所以字体信息都改成了雅黑的信息。原版misans可在小米官网下载一搜就有。因为这是网上下载的别人修改好的字体包，所以如果只是这个字体包的问题的话，我可以换别的字体使用。

已经测试字体  _Mi Sans_ 可以正常显示。附下载地址：[ Mi Sans ](https://pan.quark.cn/s/eaa76e8d5497)
