### ISSUE TITLE
可以自己指定播放器路径吗

### ISSUE THREAD

**Issue by zhengqwe** [InfpHub/Raptor#16]
MPV/VLC/PotPlayer我都有，我不想再装另一个了...

**Comment by InfpPointPlus** [comment]
> MPV/VLC/PotPlayer我都有，我不想再装另一个了...

可以的，在 _设置 - 播放 - 双击您要设置路径的播放器的“路径” 然后填入您计算机中可执行文件的路径即可。如：C:/mpv.exe_ 。
