### ISSUE TITLE
登录失败怎么解决？

### ISSUE THREAD

**Issue by 1106458351** [InfpHub/Raptor#22]
![PixPin_2024-02-23_02-00-04](https://github.com/InfpPointPlus/Raptor/assets/86955226/bcd038d0-7543-47ab-b7ff-3f0fb6f9b598)

**Comment by InfpPointPlus** [comment]
> ![PixPin_2024-02-23_02-00-04](https://github.com/InfpPointPlus/Raptor/assets/86955226/bcd038d0-7543-47ab-b7ff-3f0fb6f9b598)
> 

抱歉，给您带来不好的体验！

该问题在部分计算机中会出现，为 C++ 字符串转 C 字符串导致。但并非所有计算机均会出现。下个版本将会进行修复。

**Comment by Zodix** [comment]
我也是同样的问题，期待大佬的更新！

**Comment by HenryWu01** [comment]
我也是同样的问题，具体日志如下:
```
2024-03-05 21:10:46.170   ERROR 29560 --- [34316] RaptorAuthenticationSuite::invokeItemDetailFetch        : 274 "URL using bad/illegal format or missing URL"
2024-03-05 21:10:46.170   ERROR 29560 --- [34316] RaptorAuthenticationSuite::onItemQrCodeStatusFetching   : 621 "URL using bad/illegal format or missing URL"
```

**Comment by HenryWu01** [comment]
> 我也是同样的问题，具体日志如下:
> 
> ```
> 2024-03-05 21:10:46.170   ERROR 29560 --- [34316] RaptorAuthenticationSuite::invokeItemDetailFetch        : 274 "URL using bad/illegal format or missing URL"
> 2024-03-05 21:10:46.170   ERROR 29560 --- [34316] RaptorAuthenticationSuite::onItemQrCodeStatusFetching   : 621 "URL using bad/illegal format or missing URL"
> ```

2024.2.0 依旧存在此问题

**Comment by InfpHub** [comment]
> > 我也是同样的问题，具体日志如下:
> > 
> > ```
> > 2024-03-05 21:10:46.170   ERROR 29560 --- [34316] RaptorAuthenticationSuite::invokeItemDetailFetch        : 274 "URL using bad/illegal format or missing URL"
> > 2024-03-05 21:10:46.170   ERROR 29560 --- [34316] RaptorAuthenticationSuite::onItemQrCodeStatusFetching   : 621 "URL using bad/illegal format or missing URL"
> > ```
> 
> 2024.2.0 依旧存在此问题

您好，我的微信 14400147。可以使用您的账号调试一下吗？
