### ISSUE TITLE
1.无法按文件名称进行排序 2.整体界面字体偏小 3.“私有”与“公开”内容一样，不理解既然内容一样，为什么还要区分开来 4.UI主题切换必须重启应用才能生效，应给以注明（重启生效）

### ISSUE THREAD

**Issue by sooyaaabo** [InfpHub/Raptor#26]

**Comment by InfpPointPlus** [comment]
> 

暂未提供排序功能

样式表是开放的，可自由修改

那是代表资源盘和备份盘，哪里一样了？

FAQ 里有关于部分配置需要重启的说明

**Comment by sooyaaabo** [comment]
但是我安装后，私有与公开都是显示的是资源盘，没有备份盘，是不是bug呢

**Comment by sooyaaabo** [comment]
![屏幕截图 2024-02-24 114430](https://github.com/InfpPointPlus/Raptor/assets/76434723/95c6528d-5d9d-4ab1-8a69-5af9f558357c)
![屏幕截图 2024-02-24 114419](https://github.com/InfpPointPlus/Raptor/assets/76434723/54f17b1b-838b-4cc3-b5b0-c402e34d5340)

**Comment by sooyaaabo** [comment]
我尝试退出重新登录，仍是一样

**Comment by InfpPointPlus** [comment]
> 我尝试退出重新登录，仍是一样

回头我看下，感谢反馈！

**Comment by sooyaaabo** [comment]
![屏幕截图 2024-03-16 085911](https://github.com/InfpHub/Raptor/assets/76434723/4f469ed9-5b37-4cbd-8af8-a0bd67959f39)
![屏幕截图 2024-03-16 085904](https://github.com/InfpHub/Raptor/assets/76434723/f5cc28dd-b9ee-46ae-8e3a-84d635334553)
新版本2.0 备份盘和资源盘仍是都显示资源盘的内容

**Comment by InfpHub** [comment]
> ![屏幕截图 2024-03-16 085911](https://github.com/InfpHub/Raptor/assets/76434723/4f469ed9-5b37-4cbd-8af8-a0bd67959f39)
> ![屏幕截图 2024-03-16 085904](https://github.com/InfpHub/Raptor/assets/76434723/f5cc28dd-b9ee-46ae-8e3a-84d635334553)
> 新版本2.0 备份盘和资源盘仍是都显示资源盘的内容

在我的账号下备份盘与资源盘功能正常。您能提供更多的详细信息吗

**Comment by sooyaaabo** [comment]
![photo_2024-03-16_09-36-43](https://github.com/InfpHub/Raptor/assets/76434723/3dc24121-41f3-4945-ada8-6a0e62040efd)
![屏幕截图 2024-03-16 093538](https://github.com/InfpHub/Raptor/assets/76434723/26f08556-dc6c-4757-939c-00f7db57ee53)
我看到部分第三方客户端（例如小白羊）会要求扫码两次，第一次扫码登录，第二次扫码授权，可以勾选备份盘和资源盘（附图所示），会是这个的原因吗

**Comment by InfpHub** [comment]
> ![photo_2024-03-16_09-36-43](https://github.com/InfpHub/Raptor/assets/76434723/3dc24121-41f3-4945-ada8-6a0e62040efd)
> ![屏幕截图 2024-03-16 093538](https://github.com/InfpHub/Raptor/assets/76434723/26f08556-dc6c-4757-939c-00f7db57ee53)
> 我看到部分第三方客户端（例如小白羊）会要求扫码两次，第一次扫码登录，第二次扫码授权，可以勾选备份盘和资源盘（附图所示），会是这个的原因吗

如果移动端存在资源盘和备份盘，那应该是正常的。您方便吗？如果可以的话用您的账号我这边调试下。我的 QQ 和微信: 14400147

**Comment by sooyaaabo** [comment]
抱歉，因一些私人原因，可能不太方便。
