### ISSUE TITLE
[建议]考虑用阿里云盘开放平台openapi吗

### ISSUE THREAD

**Issue by ohmyharry** [InfpHub/Raptor#27]
如题，发现用的是web接口

**Comment by InfpHub** [comment]
> 如题，发现用的是web接口

在 2023.07 写下第一行代码的时候，曾通过官方提供的入口填写问卷以获得 OpenAPI 的使用。然该请求一去不复返。

您很在意 WebAPI 吗？OpenAPI 好多功能没有，即使接入，那也得混合一部分 WenAPI，这样需要扫描两次二维码以登录。后续还想抓一下移动端，看看有什么好玩的接口。

**Comment by ohmyharry** [comment]
@InfpHub 请问方便回个信吗我的邮箱 ohmyharry@gmail.com ，想请教一些问题不占用这里的注意力啦
