### ISSUE TITLE
无法登录，提示"URL using bad/illegal format or missing URL"

### ISSUE THREAD

**Issue by zjxdiu** [InfpHub/Raptor#3]
尝试扫码登录时报错，截图如下：
![图片](https://github.com/InfpPointPlus/Raptor/assets/52146001/42d9057a-8490-49ef-99b3-0b0efad35672)

日志文件如下
[Raptor.log](https://github.com/InfpPointPlus/Raptor/files/14326634/Raptor.log)

Integrated和Standalone版均出现此问题。

**Comment by InfpPointPlus** [comment]
已确定为 Qt 字符串转 C 风格导致该错误，此问题并非在所有计算机中都会发生，下个版本修复。

**Comment by 102060791** [comment]
win10，出现同样问题。

**Comment by wulvsky** [comment]
win11 同样的问题. 期待下个版本

**Comment by zong86** [comment]
1

**Comment by InfpHub** [comment]
Raptor 2024.2.0 现已发布，并在该版本中尝试了修改。请下载 2024.2.0 版本。
