### ISSUE TITLE
[建议] 二维码周围增加一圈白色 (Padding)

### ISSUE THREAD

**Issue by HenryWu01** [InfpHub/Raptor#31]
在深色模式下，阿里云盘移动版似乎很难识别出来二维码。而换成亮色模式则可以很轻松的识别出来。尝试使用微信扫描二维码，无论在浅色还是深色模式下均可以秒识别出来。  

之前看过说如果二维码周围有一圈留白的话，会比较好识别出来？如果周围都是深色的情况下，已经不记得是哪里看过的了，但是感觉会有点帮助。

![brave_9wu10Of982](https://github.com/InfpHub/Raptor/assets/99880210/31682b91-58f6-4456-b625-2aa1800b4065)

大概类似于这样的效果，里面的框是二维码，外面的那个框里面是白色的背景。

只是我个人的想法，如有错误，请多包涵

**Comment by InfpHub** [comment]
> 在深色模式下，阿里云盘移动版似乎很难识别出来二维码。而换成亮色模式则可以很轻松的识别出来。尝试使用微信扫描二维码，无论在浅色还是深色模式下均可以秒识别出来。  
> 
> 之前看过说如果二维码周围有一圈留白的话，会比较好识别出来？如果周围都是深色的情况下，已经不记得是哪里看过的了，但是感觉会有点帮助。
> 
> ![brave_9wu10Of982](https://github.com/InfpHub/Raptor/assets/99880210/31682b91-58f6-4456-b625-2aa1800b4065)
> 
> 大概类似于这样的效果，里面的框是二维码，外面的那个框里面是白色的背景。
> 
> 只是我个人的想法，如有错误，请多包涵

感谢您的宝贵建议。明白您的想法。要增加空白区域以增加识别度。但 UI 上可能不是特别好看。下个版本将尝试更改二维码颜色以和暗色主题区分。

**Comment by InfpHub** [comment]
Raptor 2024.2.0 现已发布！优化了暗色主题下的二维码识别度。
