### ISSUE TITLE
建议：允许使用其他的播放器播放流视频 / 不捆绑三个播放器

### ISSUE THREAD

**Issue by kaixinol** [InfpHub/Raptor#33]
比如说`MPC-HC`

**Comment by InfpHub** [comment]
> 比如说`MPC-HC`

该播放器可以命令行传递 url 进行播放么？如果可以将添加配置自定义播放器的功能。

**Comment by kaixinol** [comment]
> > 比如说`MPC-HC`
> 
> 该播放器已经于 2017 年停止更新。可以命令行传递 url 进行播放么？如果可以将添加配置自定义播放器的功能。

有后续维护者 https://github.com/clsid2/mpc-hc
可以的

**Comment by Aalivexy** [comment]
不希望捆绑播放器+1
大部分人其实都用不到**三个**播放器，对播放器有需求的玩家显然自己也会下载使用适合自己的播放器

**Comment by InfpHub** [comment]
> 不希望捆绑播放器+1 大部分人其实都用不到**三个**播放器，对播放器有需求的玩家显然自己也会下载使用适合自己的播放器

好的，2024.2.0 中将会仅提供第三方播放器的自定义配置。

**Comment by skywk** [comment]
如何选择其他的播放器呢？

**Comment by UnWaitingGo** [comment]
@InfpHub 请问一下这个就是错误的原因就是因为没有播放器，需要自己配置吗？
![Uploading 1.png…]()

**Comment by UnWaitingGo** [comment]
@InfpHub 请问一下这个就是错误的原因就是因为没有播放器，需要自己配置吗？
![1](https://github.com/InfpHub/Raptor/assets/152796127/bccf2126-77da-4fc8-b189-c17470ac57f6)

**Comment by UnWaitingGo** [comment]
> @InfpHub 请问一下这个就是错误的原因就是因为没有播放器，需要自己配置吗？ ![1](https://private-user-images.githubusercontent.com/152796127/346261543-bccf2126-77da-4fc8-b189-c17470ac57f6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAyNTQ0OTAsIm5iZiI6MTcyMDI1NDE5MCwicGF0aCI6Ii8xNTI3OTYxMjcvMzQ2MjYxNTQzLWJjY2YyMTI2LTc3ZGEtNGZjOC1iMTg5LWMxNzQ3MGFjNTdmNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwNlQwODIzMTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YzI5N2Q1NTc3NGZmMzBlMzVhMmU4YWU5ZmEyMzE5ODkxZGU0MjVhODFlN2RmZjJjOTU1MGEzZDI4NmJmNTFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GWdOOWBeSLIOSqph9k6P6jYtKlP19wNOFq4G2qxdQGo)
您的项目虽然删库了，但是我认为还有很多值得学习的地方。。之前有保留了一份，，，，
