### ISSUE TITLE
请求添加对夸克网盘的支持

### ISSUE THREAD

**Issue by Raudience** [InfpHub/Raptor#9]
由于夸克的某个推广计划，夸克现在资源量和用户数都不输阿里云盘了，希望可以添加支持

**Comment by InfpPointPlus** [comment]
这个是阿里云盘的第三方客户端。您是想让我编写一款夸克云盘的第三方客户端嘛？😳

**Comment by Raudience** [comment]
集成一下呗，如果一个软件可以用两个网盘，感觉是一件美事呀，让我少下载一个软件。😊
我有想法，就提了嘛，如果不可以，那就当我没说。
